services:
  node:
    image: node:16-alpine
    container_name: blogcms_node
    working_dir: /app/blog_front
    volumes:
      - ./blog_front:/app/blog_front
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - web
