name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run pre-commit
        run: pre-commit run --all-files --color always

      - name: Apply migrations
        run: python manage.py migrate --noinput

      - name: Run Django tests
        run: python manage.py test

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Node dependencies
        run: |
          cd blog_front
          npm install

      - name: Run Node tests
        run: |
          cd blog_front
          npm test -- --runInBand
