name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python deps
        run: |
          pip install -r requirements.txt
      - name: Run Django tests
        run: |
          python manage.py test
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install Node deps
        run: |
          cd blog_front && npm install
      - name: Run Jest
        run: |
          cd blog_front && npm test -- --runInBand
